### PR TITLE
Fix #324

### LINKED ISSUE #324: Windows mingw compile error on oatppAllTests project
ConnectionProvider.cpp:300:5: error: 'inet_ntop' was not declared in this scope inet_ntop(AF_INET, &sockAddress->sin_addr, strIp, INET_ADDRSTRLEN);
Windows, MinGW64, g++, cmake, clion

### PR DESCRIPTION
**Pull request by wvffle**
https://github.com/oatpp/oatpp/issues/324#issuecomment-711065560 describes how MinGW is failing to build due to its Windows XP support and this PR implements the failing function based on the code from https://www.mail-archive.com/users@ipv6.org/msg02107.html.

### CODE REVIEW

File: src/oatpp/network/tcp/server/ConnectionProvider.cpp [hunk 1]
```diff
@@ -43,6 +43,29 @@
   #endif
 #endif
 
+#if _WIN32_WINNT < 0x0600
```
Comment (bamkrs) [inline src/oatpp/network/tcp/server/ConnectionProvider.cpp:46]: Could you wrap the whole `#if` block in another check for an MinGW build like `#ifdef __MINGW32__
`? For linux compiler `#if _WIN32_WINNT < 0x0600` evaluates to true because the `_WIN32_WINNT` macro is not set.

File: src/oatpp/network/tcp/server/ConnectionProvider.cpp [hunk 2]
```diff
@@ -43,6 +43,29 @@
...
+  const char * inet_ntop (int af, const void *src, char *dst, socklen_t cnt) {
```
Comment (bamkrs) [inline src/oatpp/network/tcp/server/ConnectionProvider.cpp:47]: Also, could you note where this code comes from? We should at least attribute the original author with a link to its original work.

**Review by bamkrs — CHANGES_REQUESTED** [review]
Nice! Just two minor changes and I think we are ready to go!

**Review by lganzzzo — APPROVED** [review]
Looks good!

**Review by bamkrs — APPROVED** [review]
Nice!

**Comment by bamkrs** [comment]
Good work @wvffle ! Now we can add MinGW in our compatibility list. This is a huge profit for Oat++ and a vast amount of potential users. Thank you.

**Comment by wvffle** [comment]
> Good work @wvffle ! Now we can add MinGW in our compatibility list. This is a huge profit for Oat++ and a vast amount of potential users. Thank you for your contribution!

Glad to hear that :)
